Павельев Иван
urfu-2018/markup-task-2 pull request #104
Opened 2018-10-18 11:00 UTC by Pavelevivan

[Посмотреть решение](https://hruview.herokuapp.com/Pavelevivan/markup-task-2/master/index.html)

2018-10-18 11:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 11:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 10:03 UTC, SemyonMakhaev requested changes
🍅 

Привет! Молодец, очень классное решение 20-го задания 👍

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/1.html
> +                background-color: #6698ff;
Правило дублируется, можно сгруппировать селекторы

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/1.html
> +</html>
Почему всё съехало? 😅

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/11.html
> +                    border: 3px solid #6698ff;
В трёх селекторах разница только в цвете границы. Можно не переназначать остальные свойства

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/12.html
> +                div
Этот селектор работает для всех `div`, и переназначается для тех, которые `:empty`. Можно сузить выборку в селекторе

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/13.html
> +                div:only-of-type
👍

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/16.html
> +                div.c1
Тег в селекторе класса указывать не обязательно. Можно повысить специфичность, указав в селекторе родительский класс

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/17.html
> +                outline: none !important;
Давай попробуем обойтись без `!important`. В селекторе выше можно выбрать только те `input`, у которых нет атрибута `:checked`

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/18.html
> +                    opacity: 1 !important;
Получится ли здесь обойтись без `!important`? Можно повысить специфичность правила, указав родителя

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/19.html
> +                    background-color: white;
Не мешай разные способы задания цвета в одном проекте. Используй `hex`, он более универсален

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/2.html
> +                border: 2px solid #000;
Это лишнее правило, оно указано в селекторе класса `.c1`, а первый `div` содержит этот класс

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/20.html
> +                div:nth-last-child(3) ~ div > div
👍 👍 👍

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/3.html
> +                    border: none;
Можно не перебивать правило для границы, если в селекторе выше выбрать не все `div`, а только первого потока `.global-scope`

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/6.html
> +                    color: #ff6898;
Правила в селекторах совпадают. Можно обойтись одним селектором, если выбрать все элементы, у которых в теге `href` содержится `yandex`

2018-10-24 10:03 UTC, SemyonMakhaev commented on tasks/7.html
> +                div:nth-child(3)
Обрати внимание, что у некоторых картинок указан атрибут `alt`

2018-10-27 12:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-27 12:20 UTC, SemyonMakhaev approved these changes
🍏 👍

2018-10-27 12:20 UTC, closed without merging