Акишкина Вероника
urfu-2018/markup-task-2 pull request #108
Opened 2018-10-18 11:32 UTC by AirenLaird

Квадратики раскрашены и не только

2018-10-18 11:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 11:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 12:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 12:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 05:46 UTC, AirenLaird commented
:bell:

2018-10-25 05:47 UTC, AirenLaird commented
Последний же день для проверки ментором

2018-10-25 20:18 UTC, SemyonMakhaev requested changes
🍅 

Привет! Я почти успел 😅 
Извини ещё раз пожалуйста за долгое ревью

Молодец, что разобралась с селекторами! Круто, что сделала 20-ое задание 👍 
Есть несколько замечаний. Если будут вопросы, пиши мне в слаке)

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/1.html
> +                    background: #6698ff;
Правило дублируется, можно сгруппировать селекторы

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/1.html
> +                div.c1
В селекторе класса не обязательно указывать тег. Посмотри в остальных заданиях, можно ли где-то тоже обойтись без указания тега

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/1.html
> +                    background: #6698ff;
Для задания цвета достаточно использовать правило `background-color`

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/12.html
> +                div:nth-child(2n)
Попробуй использовать здесь псевдокласс [empty](http://htmlbook.ru/css/empty)

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/13.html
> +                div:nth-of-type(2n+5) > div
Получится ли упростить селекторы, если использовать [only-of-type](http://htmlbook.ru/css/only-of-type)?

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/16.html
> +                    background: #ff6698 !important;
Это правило достаточно применить только для первого `div`

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/16.html
> +                    background: #6698ff !important;
Давай попробуем по максимуму упразднить `!important`. Например, в этом селекторе ты можешь повысить специфичность правила, указав класс родительского элемента

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/17.html
> +                input:nth-child(n+6)
В это задании предполагается, что правило применяется ко всем чекбоксам без псевдокласса `checked`, следующих за чекбоксом, который `checked`. Здесь подойдёт селектор "[родственного элемента](http://htmlbook.ru/css/selector/sibling)"

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/20.html
> +                div:nth-child(n+3) div
👍 👍 👍

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/4.html
> +                article:not(:nth-of-type(-n+1))
Молодец, что разобралась с `nth-child` и `nth-of-type`!

Но селектор получается очень сложным для вычислений и для понимания. Можно ли упростить, используя оператор `+`?

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/5.html
> +                div
Предполагается, что элемент имеет тёмную и светлую тему, которые переключаются при помощи чекбокса. Можно использовать псевдокласс `checked`

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/7.html
> +                [src='http://www.codingdojo.com/blog/wp-content/uploads/css.jpg']:not([alt])
Можно просто указать тег)
```suggestion
                img:not([alt])
```

2018-10-25 20:18 UTC, SemyonMakhaev commented on tasks/9.html
> +                a[href]
Ссылки снизу тоже покрасились 😄 
Чтобы такого не происходило, старайся избегать общих селекторов (в частности, селекторов тегов в пользу селекторов классов)

![css_selektors_2000_2018-10-26_01-14-14](https://user-images.githubusercontent.com/18099714/47527686-90d30580-d8bc-11e8-81a9-968272a95ef7.png)

2018-10-26 03:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-26 04:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-26 04:19 UTC, AirenLaird commented
🔔 По замечаниям ('+' = исправила; '?' = вопрос к вам):
1) +;
2) +;
3) + (Посмотрела разницу между background и background-color, почитала про другие свойства типа 'backgraund-...', но в markup-task-3 я тоже использовала просто background и уже отправила, не серчайте);
4) +;
5) + (Как же все бывает просто);
6) ? Наверное вы имели в виду не для первого div, а для последнего. Переделала, посмотрите;
7) ? Сейчас в итоге оставлен один '!important', чтобы inline-стиль перебить у последнего div и все;
8) + (Когда делала, не поняла суть задания, забыла вернуться к нему);
9) + (Не думаю, что пальчики вверх, это замечание)))
10) + (Сначала хотела сделать 'article article + article', а потом поняла, что можно короче);
11) +;
12) +;
13) + (Ой ^^", мое разрешение экрана не дало мне этого заметить);

2018-10-26 04:31 UTC, SemyonMakhaev approved these changes
🍏 🔥

2018-10-26 04:32 UTC, closed without merging