Маргарита Никишина
urfu-2018/markup-task-2 pull request #109
Opened 2018-10-18 11:32 UTC by MargaritaNik

2018-10-18 11:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-28 17:14 UTC, spt30 requested changes
🍅 Привет! Ты сдала задачу за час до дедлайна тестов, + неделя менторская
Продлеваю дедлайн до 4 ноября 23:32

2018-10-28 17:14 UTC, spt30 commented on tasks/1.html
> +                aside
можно объединить в одно css-правило с верхним

2018-10-28 17:14 UTC, spt30 commented on tasks/11.html
> +                input:last-child
здесь задание следует трактовать так: при вводе в любое из полей валидного или невалидного email, инпут красится в соответствующий цвет, порядок и количество роли не играют

2018-10-28 17:14 UTC, spt30 commented on tasks/11.html
> +                input:first-child:focus
фокус тоже для обоих инпутов

2018-10-28 17:14 UTC, spt30 commented on tasks/12.html
> +                div:nth-child(odd):not(:nth-child(5))
есть другое отличие у дивов, смотри внимательно в код и не завязывайся на порядок

2018-10-28 17:14 UTC, spt30 commented on tasks/16.html
> +                background: #ffb366 !important;
можно обойтись без important почти везде

2018-10-28 17:14 UTC, spt30 commented on tasks/18.html
> +                div:not(:hover)
при наведении на квадратик, остальные должны становиться тусклее, а он сам – ярче

2018-10-28 17:14 UTC, spt30 commented on tasks/19.html
> +                div:nth-child(1) > div:last-child
:first-child выглядит читабельнее, чем :nth-child(1)

2018-10-28 17:14 UTC, spt30 commented on tasks/19.html
> +                div:nth-child(4) > div:first-child
здесь то же самое, только :last-child

2018-10-28 17:14 UTC, spt30 commented on tasks/19.html
> +                div:nth-child(2) > div:nth-child(2n)
можно использовать odd и even, так читаемее

2018-10-28 17:14 UTC, spt30 commented on tasks/2.html
> +                    border: 2px solid #000;
если ты уберешь это css-свойство, ничего не поменяется, ты его описываешь ниже повторно

2018-10-28 17:14 UTC, spt30 commented on tasks/20.html
> +                div:nth-child(n + 3) > div
ну нееееет)) перечитай задание внимательно)

2018-10-28 17:14 UTC, spt30 commented on tasks/3.html
> +                    border: initial;
давай попробуем как-то задать бордер сразу нужным элементам, чтобы потом его не отменяться

2018-10-28 17:14 UTC, spt30 commented on tasks/6.html
> +            a:not(:first-child)
смысл задания такой: нужно добавить покрасить все яндексовые ссылки красным, а остальные – синим
При этом на порядок и количество завязываться не нужно, требуется более универсальное решение

2018-10-28 17:14 UTC, spt30 commented on tasks/7.html
> +                div:not(:first-child):not(:last-child)
тоже посмотри внимательно, чем отличаются картинки друг от друга, невзирая на порядок

2018-10-28 17:14 UTC, spt30 commented on tasks/8.html
> +                a[href*='//']:not([href*='my-site'])
подсказка: внешние ссылки открываются в новой вкладке, давай более общо опишем

2018-10-28 17:14 UTC, spt30 commented on tasks/9.html
> +                    color: gray;
а при нажатии на псевдоссылку она все равно остается серой(

2018-11-04 15:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 23:12 UTC, spt30 commented
🍏теперь все хорошо)

2018-11-04 23:12 UTC, closed without merging