Mazalov Daniil
urfu-2018/markup-task-2 pull request #11
Opened 2018-10-14 08:35 UTC by danilych-100

https://danilych-100.github.io/markup-task-2/

2018-10-14 08:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 08:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-14 09:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 09:51 UTC, nex2hex requested changes
🍅

2018-10-17 09:51 UTC, nex2hex commented on tasks/8.html
> +                a:not([href*='my-site.ru'])
не работает

2018-10-17 09:51 UTC, nex2hex commented on tasks/8.html
> +                a:not([href*='my-site.ru'])
https://yadi.sk/i/vvhB7J3YKc6K5A

2018-10-17 09:51 UTC, nex2hex commented on tasks/9.html
> +                a[href*='https://ya.ru']
при наведении на pseudolink не подсвечивается в серый
при наведении на ya.ru pseudolink становится серым

2018-10-17 09:51 UTC, nex2hex commented on tasks/11.html
> +                input[value*='invalid-email']
при `another-email` все сломается

2018-10-17 09:51 UTC, nex2hex commented on tasks/12.html
> +                .global-scope div:nth-child(1),
тут можно обойтись без nth селекторов

2018-10-17 09:51 UTC, nex2hex commented on tasks/13.html
> +                .global-scope div:nth-child(4n+1) > div:first-of-type
тут тоже

2018-10-17 09:51 UTC, nex2hex commented on tasks/18.html
> +                .global-scope > div
по ховеру на один элемент остальные должны становиться светлее

2018-10-19 05:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 15:23 UTC, closed without merging