Мокрецов Максим
urfu-2018/markup-task-2 pull request #111
Opened 2018-10-18 12:02 UTC by Apforviolet

2018-10-18 12:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 12:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 12:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 12:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 12:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 11:36 UTC, nex2hex requested changes
🍅

2018-10-22 11:36 UTC, nex2hex commented on tasks/6.html
> +                a[href='https://yandex.ru']
второй и третий селекторы можно объединить

2018-10-22 11:36 UTC, nex2hex commented on tasks/7.html
> +                article div:nth-child(n+2)
нужно решить задачу без nth

2018-10-22 11:36 UTC, nex2hex commented on tasks/8.html
> +                a[target='_blank']
селектор должен работать для внешних ссылок, а не тех, которые открываются в новом окне

2018-10-22 11:36 UTC, nex2hex commented on tasks/9.html
> +                a[href='https://ya.ru']:visited
не хватает стилей для pseudolink

`='https://ya.ru'` можно удалить, будет правильнее, что не будем искать конкретный адрес в ссылке

2018-10-22 11:36 UTC, nex2hex commented on tasks/12.html
> +                div:nth-child(2n)
надо решить без nth

2018-10-22 11:36 UTC, nex2hex commented on tasks/13.html
> +                div:nth-child(4n+1) > div:first-child
и тут

2018-10-22 11:36 UTC, nex2hex commented on tasks/15.html
> +                a[href='archive.zip']::after
можно объединить

2018-10-22 11:36 UTC, nex2hex commented on tasks/18.html
> +                div
при наведении на квадратик другие должны быть светлее

2018-10-24 20:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-26 08:46 UTC, closed without merging