Корабельников Алексей
urfu-2018/markup-task-2 pull request #125
Opened 2018-10-22 08:41 UTC by AlexKorablenikov

2018-10-22 19:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 06:45 UTC, chrighter requested changes
🍅

2018-10-24 06:45 UTC, chrighter commented on tasks/1.html
> +                    background-color: #6698ff;
Стили `div` и `aside` одинаковые

Давай их объединим

2018-10-24 06:45 UTC, chrighter commented on tasks/2.html
> +        <link rel="stylesheet" type="teborder: 2px solid#000;xt/css" href="../global.css">
Это что за `type`?

2018-10-24 06:45 UTC, chrighter commented on tasks/15.html
> +                    content: '↓';
![image](https://user-images.githubusercontent.com/22082557/47410831-7f84de80-d780-11e8-8e6e-ac895e2dad9a.png)
Не соответствует макету

2018-10-24 06:45 UTC, chrighter commented on tasks/18.html
> +                    opacity: 1;
![image](https://user-images.githubusercontent.com/22082557/47410882-9a575300-d780-11e8-8567-55c4fad854ba.png)
При наведении на один из квадратиков его цвет должен стать ярче дефолтного (у тебя это реализовано), а _цвета других квадратиков должны стать бледнее, чем дефолтный_ (у тебя это не реализовано)

На скрине навожу на центральный квадратик

2018-10-24 06:45 UTC, chrighter commented on tasks/2.html
> +                }
У `c1` и `c1 c2` отсутствует `border`

2018-10-24 06:45 UTC, chrighter commented on tasks/3.html
> +                    border: 2px solid#000;
Нужен пробел

2018-10-24 06:45 UTC, chrighter commented on tasks/8.html
> +                a[href*='//']:not([href*='my-site.ru'])
👍

2018-10-24 06:45 UTC, chrighter commented on tasks/9.html
> +                a:not([nref]):hover
`nref`?

2018-10-24 06:45 UTC, chrighter commented on tasks/5.html
> +                    background: black;
Давай задавать цвета единообразно

2018-10-24 06:45 UTC, chrighter commented on tasks/11.html
> +                    border: 3px solid #6698ff;
Стиль должен применяться при _фокусе_

2018-10-24 09:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 20:56 UTC, chrighter requested changes
🍅 

Осталось чуть-чуть

2018-10-24 20:56 UTC, chrighter commented on tasks/15.html
> +                    content: ' ↓';
Давай зададим стрелочку с помощью `utf8`-символа

2018-10-24 21:01 UTC, chrighter requested changes

2018-10-24 21:01 UTC, chrighter commented on tasks/9.html
> +                a[href]:active
При нажатии на `pseudolink` она должна стать чёрной

2018-10-25 08:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 08:10 UTC, chrighter approved these changes
🍏

2018-10-25 08:11 UTC, closed without merging