first
urfu-2018/markup-task-2 pull request #126
Opened 2018-10-24 19:01 UTC by AnastasiaSD

2018-10-24 19:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-24 19:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-25 14:53 UTC, spt30 requested changes
🍅

2018-11-25 14:53 UTC, spt30 commented on tasks/12.html
> +                div:nth-child(5n),
У дивов есть другое отличие, смотри внимательно

2018-11-25 14:53 UTC, spt30 commented on tasks/13.html
> +                div:nth-child(4n + 1) > div:first-child
И тут тоже есть отличие у покрашенных элементов

2018-11-25 14:53 UTC, spt30 commented on tasks/14.html
> +                li:before
before и after – это псевдоэлементы, а у тебя они псевдоклассы

2018-11-25 14:53 UTC, spt30 commented on tasks/18.html
> +                div:hover
При ховере элемента, все остальные должны потускнеть

2018-11-25 14:53 UTC, spt30 commented on tasks/6.html
> +                [href*='vk.ru']
здесь смысл такой: все яндексовые ссылки – красным, все неядексовые – синим, независимо от того, что в них

2018-11-25 14:53 UTC, spt30 commented on tasks/9.html
> +                a[href]:hover
из-за порядка применения css-свойств задание не работает

2019-01-01 17:48 UTC, closed without merging