Чуприлин Андрей
urfu-2018/markup-task-2 pull request #13
Opened 2018-10-14 10:00 UTC by Leofwin

2018-10-14 10:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 06:26 UTC, chrighter requested changes
🍅

2018-10-24 06:26 UTC, chrighter commented on tasks/14.html
> +                    content: '+';
![image](https://user-images.githubusercontent.com/22082557/47410277-b0fcaa80-d77e-11e8-807d-1115ad365ab1.png)
Не соответствует макету

2018-10-24 06:26 UTC, chrighter commented on tasks/4.html
> +                .global-scope_4 article:not(:first-of-type)
Давай попробуем с помощью `:nth-of-type`

2018-10-24 06:26 UTC, chrighter commented on tasks/8.html
> +                .global-scope ul li a[href*='//']:not([href*='//my-site.ru'])
👍

2018-10-24 06:26 UTC, chrighter commented on tasks/9.html
> +                    color: #000 !important;
Давай попробуем это задание решить без использования `!important`

Вообще в будущем нужно стараться избегать его использования

2018-10-24 06:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 21:57 UTC, chrighter requested changes
🍅 

Осталось чуть-чуть, ты молодец

2018-10-24 21:57 UTC, chrighter commented on tasks/4.html
> +                .global-scope_4 article:nth-of-type(n+2)
👍

2018-10-24 21:57 UTC, chrighter commented on tasks/13.html
> +                .global-scope > div:nth-child(4n+1) > div:first-of-type
Рабочее решение, но давай будем использовать псевдокласс, применяемый к дочернему элементу указанного типа, только если он единственный у родителя, посмотри внимательнее на разметку

2018-10-25 08:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-25 08:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 09:45 UTC, chrighter approved these changes
🍏

2018-10-25 09:45 UTC, closed without merging