Solved all tasks
urfu-2018/markup-task-2 pull request #14
Opened 2018-10-14 10:15 UTC by romassol

2018-10-14 10:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 08:49 UTC, romassol commented
@spt30

2018-10-25 16:44 UTC, spt30 requested changes
🍅 Привет! Ты решила задачу за 4 дня и 2 часа до дедлайна тестов, + неделя проверки ментором => продлеваю дедлайн до 5 ноября 23:45
Извини, что накапливаю тебе таски, много дел было)

2018-10-25 16:44 UTC, spt30 commented on tasks/1.html
> +                aside
можно засунуть в первый селектор

2018-10-25 16:44 UTC, spt30 commented on tasks/10.html
> +                .global-scope p.title:first-letter
это псевдоэлемент

2018-10-25 16:44 UTC, spt30 commented on tasks/10.html
> +                .global-scope p.description:first-line
и это тоже

2018-10-25 16:44 UTC, spt30 commented on tasks/10.html
> +                .global-scope p.title:first-letter
не обязательно писать `.global-scope` и полные селекторы, достаточно тут написать просто `.title:first-letter`

2018-10-25 16:44 UTC, spt30 commented on tasks/11.html
> +                .global-scope input[type='email']:valid
тут тоже можно написать просто input:valid

2018-10-25 16:44 UTC, spt30 commented on tasks/11.html
> +                    border: 3px solid #98ff66;
хорошо бы дать бордер, а потом просто менять цвет, а не весь бордер

2018-10-25 16:44 UTC, spt30 commented on tasks/13.html
> +                .global-scope div:nth-child(4n+1) div:first-child
есть другое отличие, не завязывайся на номер

2018-10-25 16:44 UTC, spt30 commented on tasks/14.html
> +                .global-scope ul li:before
before – это псевдоэлемент, а не псевдоселектор

2018-10-25 16:44 UTC, spt30 commented on tasks/14.html
> +                .global-scope ul li:before
и тоже слишком большая цепочка, пиши короче – просто `li::before`

2018-10-25 16:44 UTC, spt30 commented on tasks/15.html
> +                .global-scope ul li a[href$='.zip']:after
псевдоэлемент

2018-10-25 16:44 UTC, spt30 commented on tasks/19.html
> +                .global-scope div:nth-child(1) div:nth-child(4)
можно использовать другие псевдоселекторы вместо :nth-child(1) и :nth-child(4)

2018-10-25 16:44 UTC, spt30 commented on tasks/19.html
> +                .global-scope div:nth-child(2) div:nth-child(2n)
можно использовать odd и even

2018-10-25 16:44 UTC, spt30 commented on tasks/6.html
> +                .global-scope a[href^='https://vk.ru']
смысл задания не очевидный: нужно яндексовые ссылки выделить красным, а все остальные – синим

2018-10-25 16:44 UTC, spt30 commented on tasks/8.html
> +                .global-scope li a[href*='//']:not([href*='my-site.ru'])
есть другое отличие, посмотри внимательно на ссылки

2018-10-25 16:44 UTC, spt30 commented on tasks/8.html
> +                    color: #6698ff;
это свойство не нужно было писать, ссылки уже синие и такого цвета, какого надо

2018-10-25 16:44 UTC, spt30 commented on tasks/9.html
> +                .global-scope a[href]:active
кажется, эти стили не применяются

2018-10-25 17:40 UTC, romassol commented on tasks/8.html
> +                .global-scope li a[href*='//']:not([href*='my-site.ru'])
так там ведь в задании явно написано, что нужно выделить ссялки, которые являются внешними относительно my-site

2018-10-25 17:40 UTC, romassol commented on tasks/8.html
> +                .global-scope li a[href*='//']:not([href*='my-site.ru'])
или я что-то не так поняла?

2018-10-25 17:49 UTC, spt30 commented on tasks/8.html
> +                .global-scope li a[href*='//']:not([href*='my-site.ru'])
подсказка: внешние ссылки открываются в новой вкладке

2018-10-25 18:00 UTC, romassol commented on tasks/8.html
> +                .global-scope li a[href*='//']:not([href*='my-site.ru'])
но не всегда ведь, а так моим способом я надежно выделю только внешние

2018-10-25 18:01 UTC, romassol commented on tasks/8.html
> +                .global-scope li a[href*='//']:not([href*='my-site.ru'])
даже, если внутренние ссылки, относительно my-site, будут открываться в новом окне

2018-10-25 18:05 UTC, romassol commented on tasks/8.html
> +                .global-scope li a[href*='//']:not([href*='my-site.ru'])
ладно, если это так принципиально, я исправлю, вроде там даже легче, чем моим способом

2018-10-25 18:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 18:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 19:02 UTC, spt30 approved these changes
Разобралась, молодец)
По поводу псевдоселекторов и псевдоэлементов лучше посмотреть тут: https://webref.ru/css

А вообще отличать можно как-то так: псевдоселектор выделяет некоторые из элементов, те которые с особыми свойствами
а псевдоэлемент – это css-свойство, которое выделяет часть элемента (например, первую букву или первую строчку или плейсхолдер)

2018-10-25 19:02 UTC, spt30 commented on tasks/10.html
> +                .title:first-letter
тут так и не указала псевдоэлемент

2018-10-25 19:02 UTC, spt30 commented
🍏Молодец

2018-10-25 19:02 UTC, closed without merging