Чернецов Александр
urfu-2018/markup-task-2 pull request #19
Opened 2018-10-14 18:25 UTC by Resinchen

[Посмотреть решение](https://hruview.herokuapp.com/Resinchen/markup-task-2/master/index.html)

2018-10-14 18:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-14 18:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-20 10:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-20 10:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 18:25 UTC, spt30 requested changes
🍅Привет! Ты сдал задачу за 3 дня и 18 часов до дедлайна тестов, + неделя на проверку ментором => продлеваю дедлайн до 5 ноября 18:00

2018-10-25 18:25 UTC, spt30 commented on tasks/10.html
> +                .title:first-letter
это псевдоэлементы, а не псевдоселекторы

2018-10-25 18:25 UTC, spt30 commented on tasks/11.html
> +                input
задание понято не верно: нужно, чтобы при введение в любое поле он в зависимости от валидности становился соответствующего цвета, а при фокусе – синим

текущие значения даны для примера

2018-10-25 18:25 UTC, spt30 commented on tasks/12.html
> +                div:nth-child(odd)
есть другое отличие одних дивов от других, посмотри внимательно

2018-10-25 18:25 UTC, spt30 commented on tasks/13.html
> +                div:nth-child(4n+1) > div:first-child
опять же, завязался на порядок, есть другое отличие

2018-10-25 18:25 UTC, spt30 commented on tasks/14.html
> +                li:before
псевдоэлемент, а не псевдоселектор

2018-10-25 18:25 UTC, spt30 commented on tasks/15.html
> +                a[href$='.zip']:after
псевдоэлемент, а не псевдоселектор

2018-10-25 18:25 UTC, spt30 commented on tasks/16.html
> +                    background: #ffb366 !important;
нужно использовать important только там, где это необходимо

2018-10-25 18:25 UTC, spt30 commented on tasks/17.html
> +                    outline: transparent;
none

2018-10-25 18:25 UTC, spt30 commented on tasks/18.html
> +                .global-scope > div:hover
опять же, есть перегрузки, можно обойтись без них

2018-10-25 18:25 UTC, spt30 commented on tasks/18.html
> +</html>
за что ты с ним так?))

2018-10-25 18:25 UTC, spt30 commented on tasks/3.html
> +                    border: none;
перегружаешь
можно сразу задать бордер только там, где нужно

2018-10-25 18:25 UTC, spt30 commented on tasks/6.html
> +                a[href*='yandex.ru']
ссылки, отличные от домена яндекс, покрашены в стандартный цвет
в таске приложен набор используемых цветов

2018-10-25 18:25 UTC, spt30 commented on tasks/7.html
> +                .global-scope div:nth-child(3n)
как-то мудрено, обрати внимание на то, чем отличаются картинки друг от друга

2018-10-25 18:25 UTC, spt30 commented on tasks/9.html
> +                .link:last-child:visited
из-за порядка свойств работает некорректно

2018-10-25 19:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-26 16:18 UTC, spt30 requested changes
🍅осталась правка с email'ами, остальное не критично)

2018-10-26 16:18 UTC, spt30 commented on tasks/11.html
> +                input[value='invalid-email']
![image](https://user-images.githubusercontent.com/31798669/47578715-8ae42f80-d963-11e8-9a64-eb14ec994fd3.png)
При вводе валидного email в первое поле оно все равно светится красным
почитай про псевдоклассы тут: https://webref.ru/css, подбери нужные

2018-10-26 16:18 UTC, spt30 commented on tasks/16.html
> +                div:nth-child(even)
было же правильно)

2018-10-26 16:18 UTC, spt30 commented on tasks/7.html
> +                .global-scope img:not([alt*='css'])
можно просто img:not([alt])

2018-10-26 18:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-27 22:41 UTC, spt30 commented
🍏теперь все оч круто!

2018-10-27 22:41 UTC, closed without merging