Солодовникова Екатерина
urfu-2018/markup-task-2 pull request #2
Opened 2018-10-11 17:24 UTC by KatySolo

[Посмотреть решение](https://hruview.herokuapp.com/KatySolo/markup-task-2/master/index.html)

2018-10-11 17:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-12 13:59 UTC, nex2hex requested changes
🍅

2018-10-12 13:59 UTC, nex2hex commented on tasks/6.html
> +        a:visited
если зайти на vk.ru или не заходить на yandex.ru верстка сломается

2018-10-12 13:59 UTC, nex2hex commented on tasks/8.html
> +        a[target='_blank']
target='_blank' говорит о том, что ссылка открывается в новом окне, а не о том, внешний это ресурс или нет

2018-10-12 13:59 UTC, nex2hex commented on tasks/9.html
> +        a[href]
pseudolink по ховеру не подсвечивается в серый цвет

2018-10-12 13:59 UTC, nex2hex commented on tasks/11.html
> +        input
Не работает https://yadi.sk/i/qm1HqTEsKmWkoA

2018-10-12 13:59 UTC, nex2hex commented on tasks/12.html
> +        div
логичнее использовать :empty

2018-10-12 13:59 UTC, nex2hex commented on tasks/13.html
> +        article > div:nth-of-type(4n-3) > div:first-of-type
тут тоже надо обойтись без `nth` селекторов

2018-10-12 14:01 UTC, nex2hex commented
сорян, не заметил что с меня сняли

2018-10-13 09:00 UTC, KatySolo commented on tasks/9.html
> +        a[href]
у меня в Chrome все работает, по наведению меняется у pseudolink opacity 
я не знаю где искать ошибку

2018-10-13 09:01 UTC, KatySolo commented on tasks/11.html
> +        input
а при фокусе на второй input зеленый, тоже цвет меняется на синий?

2018-10-13 09:04 UTC, KatySolo commented on tasks/12.html
> +        div
а в каком месте? 😅
в первом селекторе?

2018-10-13 19:27 UTC, nex2hex commented on tasks/11.html
> +        input
да, порядок инпутов не важен, важно состояние

2018-10-13 19:28 UTC, nex2hex commented on tasks/12.html
> +        div
там, где  div  не содержит в себе других div

2018-10-13 19:31 UTC, nex2hex commented on tasks/9.html
> +        a[href]
задай селекторы для 
```
a:hover - для всех ссылок, включая pseudo
a[href]:hover - перекрываем стили выше
```

2018-10-15 07:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 07:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 11:14 UTC, chrighter requested changes
🍅

2018-10-23 11:14 UTC, chrighter commented on tasks/10.html
> +            color: red;
![image](https://user-images.githubusercontent.com/22082557/47353525-eac5a680-d6d5-11e8-9a37-ba15ce5df143.png)
Цвет не соответствует макету

2018-10-23 11:14 UTC, chrighter commented on tasks/4.html
> +            border-top: 1px solid black;
Давай единообразно именовать цвета

2018-10-23 11:14 UTC, chrighter commented on tasks/4.html
> +        article > article ~ article
Рабочий вариант, но давай попробуем с `nth-of-type`

2018-10-23 11:14 UTC, chrighter commented on tasks/5.html
> +            color: white;
Наверное правильнее в этой задаче именовать цвета в `hex`, если в условии уже дано в `hex`. Ведь иначе половина заданий одним способом, половина другим

2018-10-23 11:14 UTC, chrighter commented on tasks/9.html
> +        a:hover
Давай для указания стилей (где возможно) использовать классы, а не писать их в теги - ведь теги чтобы размечать структуру, а классы именно про отображение

2018-10-23 11:14 UTC, chrighter commented on tasks/17.html
> +            outline: 0 solid black;
Снова именование

2018-10-23 11:14 UTC, chrighter commented on tasks/2.html
> +            background-color: #ff6698;
Разве нельзя объединить задание `background-color` и `border `?

2018-10-23 11:14 UTC, chrighter commented on tasks/2.html
> +        div
Давай попробуем сделать, используя только классы, без тегов

2018-10-23 11:14 UTC, chrighter commented on tasks/20.html
> +        div:nth-child(n+3) > div
Давай тут тоже с классом попробуем

2018-10-23 11:21 UTC, nex2hex approved these changes

2018-10-23 12:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 20:41 UTC, chrighter requested changes
🍅

2018-10-24 20:41 UTC, chrighter commented on tasks/4.html
> +        article + article
![image](https://user-images.githubusercontent.com/22082557/47459954-daf1b380-d7f6-11e8-8895-1d97b507c9e1.png)

2018-10-24 20:41 UTC, chrighter commented on tasks/20.html
> +        .red-gt2:nth-of-type(n+3) > div
👍

2018-10-24 21:00 UTC, chrighter requested changes

2018-10-24 21:00 UTC, chrighter commented on tasks/9.html
> +        .link[href]:active
При нажатии на `pseudolink` она должна стать черной

2018-10-25 08:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 08:06 UTC, chrighter approved these changes
Молодец!
🍏

2018-10-25 08:07 UTC, closed without merging