Рожков Максим
urfu-2018/markup-task-2 pull request #27
Opened 2018-10-15 13:14 UTC by MaximRhz

2018-10-15 13:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-15 14:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 05:55 UTC, chrighter requested changes
🍅

2018-10-24 05:55 UTC, chrighter commented on tasks/11.html
> +                [value='invalid-email']:focus
![image](https://user-images.githubusercontent.com/22082557/47408699-d804ad80-d779-11e8-9c25-cd7809b3e5b7.png)
Рамочка должна стать цветом `#6698ff` при фокусе на любом инпуте

2018-10-24 05:55 UTC, chrighter commented on tasks/13.html
> +                div:only-of-type
👍

2018-10-24 05:55 UTC, chrighter commented on tasks/15.html
> +                    content: ' ↓';
Давай задавать стрелочку с помощью `utf8`-символа

2018-10-24 05:55 UTC, chrighter commented on tasks/17.html
> +                input:checked ~ input:not(:checked)
🔥🔥🔥

2018-10-24 05:55 UTC, chrighter commented on tasks/5.html
> +                    color: white;
Давай задавать цвета единообразно - если изначально в условии задачи был `hex`, то давай везде его использовать

2018-10-24 05:55 UTC, chrighter commented on tasks/8.html
> +                [target='_blank']
`target='_blank'` не говорит о том, что ссылка внешняя

2018-10-24 05:55 UTC, chrighter commented on tasks/9.html
> +                a[href='https://ya.ru']:hover
Не работает после того, как ссылка была посещена

2018-10-24 05:55 UTC, chrighter commented on tasks/4.html
> +                article:nth-child(2n)
Можно попробовать с помощью `nth-of-type`

2018-10-24 05:55 UTC, chrighter commented on tasks/20.html
> +                div > div:nth-last-child(n + 3),
Давай везде, где возможно, не будем писать стили в теги

Теги нужны, чтобы размечать структуру, а css классы как раз про отображение

2018-10-26 14:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-26 14:38 UTC, MaximRhz commented on tasks/4.html
> +                article:nth-child(2n)
не получилось :(

2018-11-08 15:07 UTC, closed without merging