Низовцев Илья
urfu-2018/markup-task-2 pull request #29
Opened 2018-10-15 20:16 UTC by ilnizov

2018-10-15 20:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-15 20:18 UTC, ilnizov commented
https://ilnizov.github.io/markup-task-2/

2018-10-16 11:12 UTC, ilnizov commented
Метка extra за 20 задание здесь ставится?)

2018-10-17 10:04 UTC, nex2hex requested changes
🍅 
есть несколько маленьких недочетов

2018-10-17 10:04 UTC, nex2hex commented on tasks/6.html
> +                a:first-of-type
лучше без `:first-of-type`

2018-10-17 10:04 UTC, nex2hex commented on tasks/8.html
> +                a[target='_blank']
нужно выделить именно внешние ссылки, а не те, где есть target blank

2018-10-17 10:04 UTC, nex2hex commented on tasks/9.html
> +                .link:last-child:hover
тут тоже без last-child

2018-10-17 10:04 UTC, nex2hex commented on tasks/9.html
> +                    color: #ff6698;
опечатка

2018-10-17 10:04 UTC, nex2hex commented on tasks/18.html
> +                div
по наведению остальные элементы должны становиться светлее

2018-10-17 10:24 UTC, ilnizov commented on tasks/9.html
> +                    color: #ff6698;
не вижу опечатки. цвет?
порядок селекторов поменял

2018-10-17 10:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 10:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 10:33 UTC, ilnizov commented
Поправил

2018-10-17 11:30 UTC, nex2hex commented on tasks/9.html
> +                    color: #ff6698;
да, все ок
сорри

2018-10-17 11:32 UTC, closed without merging