20 tasks is done
urfu-2018/markup-task-2 pull request #32
Opened 2018-10-16 08:07 UTC by Nerzull3

2018-10-16 08:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 17:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 17:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 17:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 18:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 18:39 UTC, spt30 requested changes
🍅Привет! Ты сдал задачу за 2 дня и 5 часов до дедлайна тестов, + неделя менторская => продлеваю дедлайн до 4 ноября 4:00
Извиняй, что долго не проверял, было много дел

2018-10-25 18:39 UTC, spt30 commented on tasks/11.html
> +                    border: 3px solid #ff6698;
хорошо бы задать дефолтный бордер, а далее менять только цвет границы

2018-10-25 18:39 UTC, spt30 commented on tasks/12.html
> +                .global-scope div:nth-child(5)
не завязывайся на порядок, есть другое отличие одних дивов от других, посмотри внимательно

2018-10-25 18:39 UTC, spt30 commented on tasks/13.html
> +                .global-scope > div:nth-child(4n+1) > div:first-child
тоже на порядок завязался, а есть другое отличие, смотри в код внимательнее

2018-10-25 18:39 UTC, spt30 commented on tasks/14.html
> +                li::before
респект за `::`

2018-10-25 18:39 UTC, spt30 commented on tasks/19.html
> +                .global-scope > div:nth-child(2) > div:nth-child(2n)
можно использовать odd и even

2018-10-25 18:39 UTC, spt30 commented on tasks/2.html
> +                div:nth-child(2n)
почему не засунул туда, где уже выбраны эти элементы? (у тебя выше уже есть стили для `.с1`)

2018-10-25 18:39 UTC, spt30 commented on tasks/20.html
> +            .red-gt2 > div:nth-last-child(4) ~ div
Перечитай задание внимательно, так не зачту

2018-10-25 18:39 UTC, spt30 commented on tasks/20.html
> +            .red-gt2 > div:nth-last-child(4) ~ div
Чтобы было проще, можешь поменять дивы местами и добавить новых

2018-10-25 18:39 UTC, spt30 commented on tasks/4.html
> +                .global-scope article:nth-child(2n)
even)

2018-10-25 18:39 UTC, spt30 commented on tasks/6.html
> +                a[href='https://vk.ru']
задание не очевидное, смысл такой: яндексовые ссылки – красным, остальные синим

2018-10-25 18:39 UTC, spt30 commented on tasks/7.html
> +                img
можно написать без перегрузки и в один селектор

2018-10-25 18:39 UTC, spt30 commented on tasks/9.html
> +                .link[href]:hover
чет задание вообще не фунциклирует, как надо(

2018-10-26 07:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-27 22:51 UTC, spt30 reviewed
🍅Одна маленькая правка)

2018-10-27 22:51 UTC, spt30 commented on tasks/9.html
> +                .link[href]:active
при нажатии на эту ссылку, псевдоссылка не становится черного цвета(
вообще по идее смысл задания был в том, чтобы эти две ссылки отдельно друг от друга описать в css
но раз уж ты начал завязывать одну на другую, то давай просто сделаем, чтобы при нажатии на обычную ссылку псевдоссылка становилась черной обратно, и ок будет тогда

2018-10-27 22:51 UTC, spt30 commented on tasks/9.html
> +                .link[href]:hover + .link:not([href])
можно по идее просто `.link[href]:hover + .link`
но если ты так аккуратно применяешь, наверняка проверяешь, что это псевдоссылка, то давай еще вместо `+` заюзаем `~`, бог его знает, где эта псевдоссылка там окажется)

2018-10-28 07:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-28 15:21 UTC, spt30 commented
🍏все круто)

2018-10-28 15:21 UTC, closed without merging