test
urfu-2018/markup-task-2 pull request #42
Opened 2018-10-16 16:53 UTC by AllEXEcuted

2018-10-16 16:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-16 17:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-16 17:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 12:10 UTC, nex2hex requested changes
🍅 
мелочи немного

2018-10-17 12:10 UTC, nex2hex commented on tasks/4.html
> +                article:nth-child(2n)
очень много nth селекторов
можно сделать проще

2018-10-17 12:10 UTC, nex2hex commented on tasks/8.html
> +                [target]:not([download])
нужно выделить ссылки на внешние ресурсы
ни target ни download не являются признаком внешней ссылки

2018-10-21 18:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 11:12 UTC, closed without merging

2018-10-29 08:32 UTC, AllEXEcuted commented
extra label не хватает