all markup-task-2
urfu-2018/markup-task-2 pull request #46
Opened 2018-10-16 17:54 UTC by VicClone

2018-10-16 17:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 08:20 UTC, dotokoto requested changes
Всё почти хорошо, поправь пару замечаний, и приму

2018-10-23 08:20 UTC, dotokoto commented on tasks/1.html
> +                .global-result .global-scope aside
Не обязательно везде дописывать `.global-result .global-scope`, можно ограничиться только последним селектором. Это ко всем следующим примерам тоже относится. Оставляй везде "минимальный" подходящий селектор. Тогда специфичность будет меньше, и переопределять будет проще. И работать будет скорее всего быстрее

2018-10-23 08:20 UTC, dotokoto commented on tasks/9.html
> +                .global-result .global-scope .link[href]:hover
При наведении на `pseudolink` он должен становиться полупрозрачным, сейчас этого нет

2018-10-23 08:20 UTC, dotokoto commented on tasks/20.html
> +                .red-gt2 div:first-child:nth-last-child(n+3) ~ div
Почему везде у селекторов был префикс `.global-result .global-scope`, а тут вдруг нет? ) Что-то подозрительно 🤨

2018-10-24 14:44 UTC, VicClone commented on tasks/20.html
> +                .red-gt2 div:first-child:nth-last-child(n+3) ~ div
Тут просто с .global-result .global-scope слишком длинные строчки выходили, я решил, что и так сойдет

2018-10-24 15:13 UTC, VicClone commented on tasks/1.html
> +                .global-result .global-scope aside
Убрал лишнее во всей тасках

2018-10-24 15:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 15:14 UTC, VicClone commented on tasks/9.html
> +                .global-result .global-scope .link[href]:hover
Не заметил сразу, исправил

2018-10-29 06:40 UTC, closed without merging