Виталий Дмитриев
urfu-2018/markup-task-2 pull request #48
Opened 2018-10-16 19:50 UTC by VitaliyDm

2018-10-16 19:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 19:23 UTC, spt30 requested changes
🍅В целом неплохо, но есть недочеты
Решил задачу за 1 день и 17 часов до дедлайна + неделя менторская => продлеваю дедлайн до 3 ноября 17:30

2018-10-25 19:23 UTC, spt30 commented on tasks/10.html
> +                .description::first-line
тут написал псевдоэлемент, а выше псевдоселектор)
они оба псевдоэлементы

2018-10-25 19:23 UTC, spt30 commented on tasks/11.html
> +                input[type='email']
давай перепишем здесь так, чтобы всегда, когда инпут в фокусе, он был синим, валидные/невалидные – по условию

2018-10-25 19:23 UTC, spt30 commented on tasks/12.html
> +                div:nth-of-type(5)
есть другое отличия, не завязывайся на порядок

2018-10-25 19:23 UTC, spt30 commented on tasks/13.html
> +                div:nth-of-type(4n+1) > div
тоже есть другое отличие, не завязывайся на порядок

2018-10-25 19:23 UTC, spt30 commented on tasks/14.html
> +                li:before
это псевдоэлемент, а не псевдоселектор

2018-10-25 19:23 UTC, spt30 commented on tasks/15.html
> +                [href$='.zip']:after
это тоже псевдоэлемент, а не псевдоселектор

2018-10-25 19:23 UTC, spt30 commented on tasks/18.html
> +                div:nth-of-type
что за селектор такой?

2018-10-25 19:23 UTC, spt30 commented on tasks/20.html
> +                div > div:nth-last-child(n + 2):first-child ~ div
не работает что-то

2018-10-25 19:23 UTC, spt30 commented on tasks/4.html
> +                    background: #ff66;
этот цвет развернется как #ffff6666, то есть ff red, ff green, 66 blue и 66 прозрачность

2018-10-25 19:23 UTC, spt30 commented on tasks/6.html
> +                a:visited
не верный псевдоселектор
смысл задания такой: яндексовые ссылки раскрасить красным, остальные – синим

2018-10-25 19:23 UTC, spt30 commented on tasks/7.html
> +                article > div:not(:first-of-type)
ненене, тут у картинок есть принципиальные отличия, смотри внимательно в код))

2018-10-25 19:23 UTC, spt30 commented on tasks/8.html
> +                a:not([href*='my-site.ru'])
подсказка: внешние ссылки открываются в новой вкладке

2018-10-25 19:23 UTC, spt30 commented on tasks/9.html
> +                [href]:visited
из-за порядка свойств ховер теперь не работает)

2018-11-01 10:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-01 10:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 23:55 UTC, spt30 commented on tasks/10.html
> +                .description:first-line
наоборот должно было быть))
и там, и там по 2 двоеточия)

2018-11-04 23:55 UTC, spt30 commented
🍏

2018-11-04 23:55 UTC, closed without merging