Анисимов Данил
urfu-2018/markup-task-2 pull request #54
Opened 2018-10-16 21:23 UTC by frosthamster

[Посмотреть решение](https://hruview.herokuapp.com/frosthamster/markup-task-2/master/index.html)

2018-10-16 21:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-16 21:26 UTC, frosthamster commented
20 таск сделан

2018-10-17 12:36 UTC, vaseker commented on tasks/1.html
> +                    background: #98ff66;
У id не нужно повышать специфичность)

2018-10-17 12:58 UTC, vaseker commented on tasks/17.html
> +                    outline: 1px solid #ff6698;
тут надо исключить обводку нескольких отмеченных селекторов, на скриншоте-эталоне это показано

2018-10-17 12:59 UTC, vaseker requested changes
🍅 пока что помидорка, жду правок

2018-10-17 15:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 15:18 UTC, frosthamster commented
🍏
пришлось убрать .global-scope в 17 таске, т.к. селектор слишком длинный
насколько я понял, селекторы разбивать на несколько строк нельзя?

2018-10-18 05:39 UTC, vaseker commented
Селекторы могут быть любой длины и разноситься на несколько строк, это нормально. Вопрос лишь в адекватности селекторов)

2018-10-18 05:40 UTC, vaseker commented
🍏принято

2018-10-18 05:40 UTC, closed without merging