Жизневский Никита
urfu-2018/markup-task-2 pull request #60
Opened 2018-10-17 11:48 UTC by 07Nick

2018-10-17 11:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 12:27 UTC, nex2hex requested changes
🍅

2018-10-17 12:27 UTC, nex2hex commented on tasks/2.html
> +                [class='c1 c2']
для классов есть гораздо более простой способ записи селекторов

2018-10-17 12:27 UTC, nex2hex commented on tasks/6.html
> +                [href*='yandex']
тут тэг указать надо чтобы селектор был более специфичным и матчился только на ссылки, а не по всем элементам

2018-10-17 12:27 UTC, nex2hex commented on tasks/7.html
> +                div:nth-of-type(n+2):not(:last-child)
тут надо обойтись без nth селекторов

2018-10-17 12:27 UTC, nex2hex commented on tasks/12.html
> +                div:nth-of-type(2n)
тут тоже можно обойтись без nth

2018-10-17 18:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 13:30 UTC, nex2hex commented on tasks/6.html
> +                [href*='yandex.ru']
добавь тэг `a`. чтобы селектор искал только ссылки

2018-10-18 13:31 UTC, closed without merging