Бессонов Роман
urfu-2018/markup-task-2 pull request #62
Opened 2018-10-17 12:47 UTC by Bolkonyashka

2018-10-17 12:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 13:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 15:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 06:55 UTC, chrighter requested changes
🍅

2018-10-24 06:55 UTC, chrighter commented on tasks/17.html
> +                input[type='checkbox']:checked ~ input
![image](https://user-images.githubusercontent.com/22082557/47411552-90ceea80-d782-11e8-9ff3-4541b0110be4.png)
Не соответствует макету

2018-10-24 06:55 UTC, chrighter commented on tasks/18.html
> +                    opacity: 1 !important;
Давай здесь обойдемся без `!important`

В будущем нужно стараться избегать его использование

2018-10-24 06:55 UTC, chrighter commented on tasks/8.html
> +                a:not([href*='my-site.ru']):not([href*='/http/'])
👍

2018-10-24 06:55 UTC, chrighter commented on tasks/9.html
> +                    color: rgb(133, 133, 133);
Давай задавать цвета единообразно

2018-10-24 06:55 UTC, chrighter commented on tasks/16.html
> +                    background: #ffb366 !important;
В этой задаче для всех элементов кроме `.c7` можно задать стили без `!important`

2018-10-24 06:55 UTC, chrighter commented on tasks/15.html
> +                    content: ' ↓';
Давай зададим стрелочку с помощью `utf8`-символа

2018-10-24 06:55 UTC, chrighter commented on tasks/12.html
> +                div:nth-last-child(-2n+3)
Рабочее решение, но предполагалось использование `:not(:empty)`

2018-10-24 06:55 UTC, chrighter commented on tasks/13.html
> +                div:nth-child(4n+1) > div
Рабочее решение, но давай будем использовать псевдокласс, применяемый к дочернему элементу указанного типа, только если он единственный у родителя, посмотри внимательнее на разметку

2018-10-24 10:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-24 10:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 10:42 UTC, Bolkonyashka commented
🍏 Спасибо за крутые советы, многое делается гораздо проще, чем я думал)

2018-10-24 21:37 UTC, chrighter requested changes
🍅

2018-10-24 21:37 UTC, chrighter commented on tasks/12.html
> +                div:not(:empty)
👍

2018-10-24 21:37 UTC, chrighter commented on tasks/13.html
> +                div > div:only-of-type
👍

2018-10-24 21:37 UTC, chrighter commented on tasks/17.html
> +                input[type='checkbox']:checked ~ input:not(:checked)
👍

2018-10-24 21:37 UTC, chrighter commented on tasks/9.html
> +                }
При нажатии на `pseudolink` она должна стать чёрной, как на макете

2018-10-25 08:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 08:38 UTC, Bolkonyashka commented
🍏 done!

2018-10-25 08:59 UTC, chrighter approved these changes

2018-10-25 09:01 UTC, closed without merging