Юхатский Илья
urfu-2018/markup-task-2 pull request #63
Opened 2018-10-17 12:58 UTC by creewick

2018-10-17 12:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 13:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 13:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 19:30 UTC, SemyonMakhaev requested changes
🍅 

Привет! Молодец, что решил последнее задание 👍

2018-10-22 19:30 UTC, SemyonMakhaev commented on tasks/1.html
> +                    background: #6698ff;
Правило дублируется, можно сгруппировать селекторы

2018-10-22 19:30 UTC, SemyonMakhaev commented on tasks/11.html
> +                    border: 3px solid #ff6698;
В двух нижних селекторах полностью переопределяется правило, задающее стили для границы в первом селекторе, хотя разница только в цвете этой границы. Можно в селекторах с псевдоклассами `:invaid` и `:hover` переназначать только `border-color`

2018-10-22 19:30 UTC, SemyonMakhaev commented on tasks/12.html
> +                div
В селекторе ниже перебивается правило, которое уже применилось ко всем элементам с тегом `div`. Будет удачнее выбрать в данном селекторе только непустые элементы

2018-10-22 19:30 UTC, SemyonMakhaev commented on tasks/13.html
> +                div:nth-child(4n+1) > div:first-child
Обрати внимание на псевдокласс [only-of-type](http://htmlbook.ru/css/only-of-type)

2018-10-22 19:30 UTC, SemyonMakhaev commented on tasks/16.html
> +                div.c1
В селекторе класса можно не указывать тег
```suggestion
               .c1
```

2018-10-22 19:30 UTC, SemyonMakhaev commented on tasks/17.html
> +                    outline: none !important;
Попробуй в этом месте не использовать `!important`. Можно в селекторе выше выбрать инпуты, которые не имеют псевдокласса `:checked`

2018-10-22 19:30 UTC, SemyonMakhaev commented on tasks/18.html
> +                    opacity: 1 !important;
Попробуй тоже обойтись здесь без `!important`. Подсказка: можно отлавливать `:hover` на теге `article` и на теге `div`

2018-10-22 19:30 UTC, SemyonMakhaev commented on tasks/19.html
> +                    background: #ffb366;
Для указания цвета фона используй `background-color`

2018-10-22 19:30 UTC, SemyonMakhaev commented on tasks/19.html
> +                    background: white;
Не перемешивай в одном проекте разные способы указания цвета. Для единообразия лучше всегда использовать `hex`, потому что он более универсален и интуитивно понятен

2018-10-22 19:30 UTC, SemyonMakhaev commented on tasks/2.html
> +                    border: 2px solid #000;
Зачем это правило? Оно уже содержится в селекторе ниже и применится ко всем элементам с классом `c1`

2018-10-23 07:11 UTC, creewick commented on tasks/16.html
> +                div.c1
работает, только если добавить !important

2018-10-23 07:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-26 17:40 UTC, SemyonMakhaev approved these changes
🍏 

Круто! Молодец

2018-10-26 17:40 UTC, SemyonMakhaev commented on tasks/16.html
> +                    background-color: #6698ff !important;
Здесь можно обойтись без `!important`. Можно повысить специфичность правила, указав в селекторе класс родителя
```css
.global-scope .c1 { ... }
```

2018-10-26 17:40 UTC, SemyonMakhaev commented on tasks/17.html
> +                input:checked
Этот селектор точно нужен здесь?

2018-10-26 17:40 UTC, SemyonMakhaev commented on tasks/18.html
> +                div:hover
Можно обойтись без `!important`. Достаточно указать родительский тег в селекторе:
```suggestion
                article div:hover
```

Можешь почитать про вычисление специфичности здесь: https://developer.mozilla.org/ru/docs/Web/CSS/Specificity

2018-10-26 17:40 UTC, closed without merging