Ратков Максим
urfu-2018/markup-task-2 pull request #68
Opened 2018-10-17 15:23 UTC by mattgroy

[Посмотреть решение](https://hruview.herokuapp.com/mattgroy/markup-task-2/master/index.html)

2018-10-17 15:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-17 15:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 17:41 UTC, nex2hex requested changes
🍅

2018-10-17 17:41 UTC, nex2hex commented on tasks/12.html
> +                div:nth-child(2n+1)
надо реализовать без nth селекторов

2018-10-17 17:41 UTC, nex2hex commented on tasks/13.html
> +                .global-scope > div:nth-child(4n+1) > div:first-child
тут тоже

2018-10-23 15:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 15:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 15:11 UTC, closed without merging