Раджабов Роман
urfu-2018/markup-task-2 pull request #73
Opened 2018-10-17 17:20 UTC by RadzhabovRoman

[Посмотреть решение](https://hruview.herokuapp.com/RadzhabovRoman/markup-task-2/master/index.html)

2018-10-17 17:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-27 23:52 UTC, spt30 requested changes
🍅Привет! Извини, что долго не проверял, был занят
Ты решил задачу за 19 часов и 30 минут до дедлайна тестов, + неделя менторская
Продлеваю дедлайн до 5 ноября 0:30

2018-10-27 23:52 UTC, spt30 commented on tasks/1.html
> +                aside
Можно было объединить в одно css-правило с самым верхним

2018-10-27 23:52 UTC, spt30 commented on tasks/11.html
> +                [value='invalid-email']
Смысл задания: нужно сделать так, чтобы при вводе в любое из полей валидного или невалидного email, input красился в соответствующий цвет
Для этого можешь использовать специальные псевдоклассы, их список можно посмотреть тут: https://webref.ru/css

2018-10-27 23:52 UTC, spt30 commented on tasks/11.html
> +                    border: 3px solid #ff6698;
Хорошо бы заранее задать бордер, а в следующих правилах менять только цвет

2018-10-27 23:52 UTC, spt30 commented on tasks/12.html
> +                div
Можно обойтись без перегрузок с помощью псевдокласса `:not()`

2018-10-27 23:52 UTC, spt30 commented on tasks/14.html
> +                li:before
Это псевдоэлемент, а не псевдокласс

2018-10-27 23:52 UTC, spt30 commented on tasks/14.html
> +                    list-style-type: none;
Нет необходимости в этом правиле

2018-10-27 23:52 UTC, spt30 commented on tasks/15.html
> +                a[href$='.zip']:after
Тоже псевдоэлемент, а не псевдокласс

2018-10-27 23:52 UTC, spt30 commented on tasks/16.html
> +                div:empty
Зачем этот псевдокласс?

2018-10-27 23:52 UTC, spt30 commented on tasks/16.html
> +                    background: #ff6 !important;
Лишний important, тут он не нужен

2018-10-27 23:52 UTC, spt30 commented on tasks/16.html
> +                div:empty
Подсказка: обрати внимание на порядок свойств и специфичность

2018-10-27 23:52 UTC, spt30 commented on tasks/2.html
> +                    border: 2px solid #000;
Лишнее свойство

2018-10-27 23:52 UTC, spt30 commented on tasks/4.html
> +                article > :nth-child(even)
Если есть возможность не использовать вложенность, не используй
Тут можно было написать `article:nth-child(even)`

2018-10-27 23:52 UTC, spt30 commented on tasks/6.html
> +                a:first-of-type
Смысл задания в том, чтобы сделать все яндексовые ссылки красными, а любые другие – синими, независимо от порядка

2018-10-27 23:52 UTC, spt30 commented on tasks/7.html
> +                img[alt]
Что-то намудрил с картинками да так, что и картинка с примером тоже стала прозрачной

2018-10-27 23:52 UTC, spt30 commented on tasks/9.html
> +                a[href]:visited
Задание не работает, давай перепишем
Обрати внимание на порядок свойств

2018-11-02 05:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 23:33 UTC, spt30 commented on tasks/11.html
> +                input[type='email']:valid
из-за порядка css свойств, валидный инпут не окрашивается синим(

2018-11-04 23:33 UTC, spt30 commented
🍏
Отдельное спасибо за названия коммитов на русском языке)

2018-11-04 23:33 UTC, closed without merging