Чикунов Никита
urfu-2018/markup-task-2 pull request #77
Opened 2018-10-17 18:15 UTC by KoMeDiAnTNDP

2018-10-17 18:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-17 20:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 13:38 UTC, nex2hex requested changes
🍅

2018-10-18 13:38 UTC, nex2hex commented on tasks/6.html
> +                [href*='yandex.ru']
добавь тэг, чтобы селектор искал только ссылки

2018-10-18 13:38 UTC, nex2hex commented on tasks/7.html
> +                [alt*='css']
тут тоже нужен тэг картинки

2018-10-18 13:38 UTC, nex2hex commented on tasks/11.html
> +                input[value^='invalid']
зачем так, а не `:invalid`?

2018-10-18 13:38 UTC, nex2hex commented on tasks/13.html
> +                div:nth-of-type(4n + 1) > div:first-child
задачу можно решить без `nth`

2018-10-18 13:38 UTC, nex2hex commented on tasks/15.html
> +                li:not(:first-child) > a[href*='zip']:after
зачем тут li:not(:first-child) ?

2018-10-18 13:38 UTC, nex2hex commented on tasks/18.html
> +                div:not(:hover)
при ховере соседи должны становиться светлее

2018-10-18 16:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 16:56 UTC, KoMeDiAnTNDP commented
А 20 задание как - то учитывается? Или это просто для тех кто захотел?

2018-10-22 11:42 UTC, nex2hex commented
учитывается

2018-10-22 11:48 UTC, nex2hex commented on tasks/11.html
> +                input:invalid:hover
:focus

2018-10-22 11:48 UTC, nex2hex commented on tasks/11.html
> +                input[value^='email']
:valid

2018-10-22 11:49 UTC, closed without merging