Гридин Андрей
urfu-2018/markup-task-2 pull request #80
Opened 2018-10-17 18:54 UTC by Drusalyator

2018-10-17 18:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-18 14:01 UTC, nex2hex requested changes
🍅

2018-10-18 14:01 UTC, nex2hex commented on tasks/6.html
> +                [href*='yandex.ru']
добавь тэг, чтобы селектор искал атрибут только среди ссылок

2018-10-18 14:01 UTC, nex2hex commented on tasks/8.html
> +                a[target='_blank']
нужно выделить внешние ссылки, а не те, которые открываются в новом окне

2018-10-18 14:01 UTC, nex2hex commented on tasks/12.html
> +                div:nth-of-type(2n),
нужно решить без использования nth селекторов

2018-10-18 14:01 UTC, nex2hex commented on tasks/18.html
> +                div:not(:hover)
при наведении соседние элементы должны становиться светлее

2018-10-19 16:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 16:56 UTC, Drusalyator commented on tasks/18.html
> +                div:not(:hover)
Я сделал, вроде как все работает, но есть небольшая бага, что при наведении между квадратами, они все равно светлеют, не знаю как это исправить, Нужна ~ только в обратную сторону, т.е. как-то старших братьев взять

2018-10-19 17:14 UTC, Drusalyator commented
Исправил все недочеты

2018-10-22 15:24 UTC, closed without merging

2018-10-22 15:33 UTC, Drusalyator commented
А я ещё доп сделал)