Пылаев Владимир
urfu-2018/markup-task-2 pull request #85
Opened 2018-10-17 19:55 UTC by Jamboba

2018-10-17 19:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-28 00:16 UTC, spt30 requested changes
🍅Привет! Извиняй, что долго не проверял
Ты решил задачу за 17 часов до дедлайна, + неделя менторская
Продлеваю дедлайн до 4 ноября 22:00

2018-10-28 00:16 UTC, spt30 commented on tasks/1.html
> +                aside
Можно объединить это css-правило с самым верхним

2018-10-28 00:16 UTC, spt30 commented on tasks/11.html
> +                input:first-child:focus
Задание трактуется двояко, но тут нужно было написать css так, чтобы при вводе в любое поле валидного или невалидного email, input красился в соответствующий цвет
Тебе могут помочь специальные псевдоклассы, список можно посмотреть тут: https://webref.ru/css

2018-10-28 00:16 UTC, spt30 commented on tasks/12.html
> +                div:nth-child(5)
Не завязывайся на порядок элементов, у них есть другое отличие, смотри в код внимательнее

2018-10-28 00:16 UTC, spt30 commented on tasks/13.html
> +                div:nth-child(4n+1) div:first-child
Тоже есть специальное отличие, не завязывайся на порядок

2018-10-28 00:16 UTC, spt30 commented on tasks/16.html
> +                    background: #ff6 !important;
Можно important написать только тут, чтобы перебить inline-стили, в остальных правилах можно было без него

2018-10-28 00:16 UTC, spt30 commented on tasks/18.html
> +                div:hover
Нужно чтобы при наведении на один из элементов, остальные тускнели немного, надо добавить еще одно правило

2018-10-28 00:16 UTC, spt30 commented on tasks/19.html
> +                div:nth-child(2) div:nth-child(2n)
Можно использовать odd и even

2018-10-28 00:16 UTC, spt30 commented on tasks/3.html
> +                    border: initial;
Хотелось бы не отменять бордер, а сразу задать его только нужным элементам

2018-10-28 00:16 UTC, spt30 commented on tasks/4.html
> +                article ~ article
Лучше написать `+`, а не `~`, так стили не будут по 10 раз применять к элементам

2018-10-28 00:16 UTC, spt30 commented on tasks/4.html
> +                article:nth-child(2n)
even

2018-10-28 00:16 UTC, spt30 commented on tasks/5.html
> +                #checkbox:checked + br + div
А тут, напротив, лучше было написать `~`, а не `+`
Бог его знает, сколько там этих br'ов понаставят в следующий раз)

2018-10-28 00:16 UTC, spt30 commented on tasks/6.html
> +                a:not(:first-child)
В этом задании смысл такой: все яндексовые ссылки подсветить красным, а любые другие – синеньким, независимо от порядка

2018-10-28 00:16 UTC, spt30 commented on tasks/7.html
> +                div:not(:first-child):not(:last-child)
Не, тут тоже есть особенность у прозрачных картинок, смотри внимательнее

2018-10-28 00:16 UTC, spt30 commented on tasks/8.html
> +                a[href*='//']:not([href*='my-site'])
Подсказка: внешние ссылки будут открываться в новой вкладке, давай на это завяжемся

2018-10-28 00:16 UTC, spt30 commented on tasks/9.html
> +                a:hover
Чет решение не фунциклирует, как надо
Обрати внимание на порядок css-правил и специфичность селекторов

2018-11-04 13:27 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 23:26 UTC, spt30 commented on tasks/5.html
> +                #checkbox:checked ~ br ~ div
вообще я имел в виду, что можно просто `#checkbox:checked ~ div`, ну да ладно

2018-11-04 23:27 UTC, spt30 commented
🍏

2018-11-04 23:27 UTC, closed without merging