Холкин Антон
urfu-2018/markup-task-2 pull request #86
Opened 2018-10-17 19:57 UTC by hukopo

2018-10-17 19:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-19 05:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-28 15:59 UTC, spt30 requested changes
🍅Почти все круто, несколько замечаний есть
Старайся писать css короче, в частности, почти везде не обязательно объявлять родительский класс

По поводу дедлайна: ты решил задачу за 17 часов до дедлайна тестов, + неделя менторская
Продлеваю дедлайн до 5 ноября 14:00

2018-10-28 15:59 UTC, spt30 commented on tasks/11.html
> +            .global-scope input:first-child
смысл этого задания в том, чтобы при вводе в любое поле валидного или . невалидного email, инпут раскрашивался соответствующим цветом, независимо от порядка и количества полей
тебе могут помочь специальные псевдоклассы

2018-10-28 15:59 UTC, spt30 commented on tasks/18.html
> +                .global-scope div:not(:hover)
здесь нужно было при наведении на один из блоков, остальные делать тусклее, а его – ярче

2018-10-28 15:59 UTC, spt30 commented on tasks/20.html
> +                .global-scope div + div + div div
Перечитай задание внимательно, так не зачту

2018-10-28 15:59 UTC, spt30 commented on tasks/3.html
> +                    border: none;
хорошо бы написать css так, чтобы обойтись без отмены стилей, а чтобы сразу применялись только необходимые

2018-10-28 15:59 UTC, spt30 commented on tasks/4.html
> +                .global-scope article:nth-child(odd)
хитрый ход, молодец)

2018-10-28 15:59 UTC, spt30 commented on tasks/6.html
> +                .global-scope a[href*='yandex.ru']
смысл задания такой: нужно сделать так, чтобы яндексовые ссылки были красными, а любые другие – синими

2018-10-28 15:59 UTC, spt30 commented on tasks/9.html
> +            a:not([href]):hover
при нажатии на псевдоссылку цвет не меняется обратно

2018-11-01 10:17 UTC, hukopo commented on tasks/9.html
> +            a:not([href]):hover
На время нажатия меняется

2018-11-01 10:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 23:22 UTC, spt30 commented
🍏

2018-11-04 23:22 UTC, closed without merging