Маклакова Елена
urfu-2018/markup-task-2 pull request #95
Opened 2018-10-18 04:41 UTC by elena-i-m98

2018-10-18 04:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 04:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 05:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 07:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 06:17 UTC, chrighter requested changes
🍅

2018-10-24 06:17 UTC, chrighter commented on 1.html
> +                aside {
У `aside` и `div` одинаковые стили

Давай их объединим

2018-10-24 06:17 UTC, chrighter commented on 8.html
> +                a:not([href*="my-site.ru"]) {
![image](https://user-images.githubusercontent.com/22082557/47409265-b3a9d080-d77b-11e8-98c4-2e627d53ccfa.png)
Не соответствует макету

2018-10-24 06:17 UTC, chrighter commented on 9.html
> +                a[href].link:hover{
Не работает после того, как ссылка была посещена

2018-10-24 06:17 UTC, chrighter commented on tasks/15.html
> +                    content: '\2193';
![image](https://user-images.githubusercontent.com/22082557/47409373-fec3e380-d77b-11e8-9969-efd9d584a6cc.png)
Не соответствует макету

2018-10-24 06:17 UTC, chrighter commented on tasks/17.html
> +                input:checked ~ input
![image](https://user-images.githubusercontent.com/22082557/47409481-4e0a1400-d77c-11e8-89ce-718446540102.png)
Не соответствует макету

2018-10-24 06:17 UTC, chrighter commented on tasks/7.html
> +                img[alt*='css']
Молодец, что смотришь на `alt`, но кажется, что с помощью `:not` можно заменить твои два условия на одно

2018-10-24 06:17 UTC, chrighter commented on tasks/20.html
> +                div div:nth-last-child(n+3):first-child ~ div
Давай везде, где возможно в задаче, не будем писать стили в теги, а использовать данные в разметке классы

Ведь теги созданы, чтобы размечать структуру, а `css` классы как раз про отображение

2018-10-24 06:17 UTC, chrighter commented on 12.html
> +                div:not(:empty) {
👍

2018-10-24 06:17 UTC, chrighter commented on 13.html
> +                article div div:first-child:only-of-type {
👍

2018-10-24 06:17 UTC, chrighter commented on 15.html
> +                    content: '\2193';
👍

2018-10-24 06:17 UTC, chrighter commented on 16.html
> +                    background: #ffff66 !important;
Здесь можно записать цвет с помощью сокращенной записи - просто `#ff6`

2018-10-25 11:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 12:44 UTC, chrighter requested changes
🍅

2018-10-25 12:44 UTC, chrighter commented on tasks/4.html
> +                article article:nth-child(2n+1)
![image](https://user-images.githubusercontent.com/22082557/47500529-7a0cbe80-d87c-11e8-92bb-9a217b663fb4.png)
Не соответствует макету

2018-10-25 12:44 UTC, chrighter commented on tasks/7.html
> +                img[alt*='css']
👍

2018-10-25 12:44 UTC, chrighter commented on tasks/8.html
> +                a[target='_blank']
У тебя была правильной идея с `not([href*="my-site.ru"]`, нужно просто довести до конца

`target='_blank'` не говорит о том, что ссылка внешняя

2018-10-25 17:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-25 17:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-27 12:34 UTC, chrighter approved these changes
🍏

2018-10-27 12:35 UTC, closed without merging