Серов Егор
urfu-2018/markup-task-2 pull request #98
Opened 2018-10-18 08:26 UTC by Jueblack

[Посмотреть решение](https://hruview.herokuapp.com/Jueblack/markup-task-2/master/index.html)

2018-10-18 08:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 08:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 09:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 09:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 09:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-18 09:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 12:28 UTC, chrighter requested changes
🍅

2018-10-23 12:28 UTC, chrighter commented on tasks/10.html
> +                    color: red;
![image](https://user-images.githubusercontent.com/22082557/47358691-ef915700-d6e3-11e8-8524-d994ff882a6c.png)
Цвета не соответствуют макету

2018-10-23 12:28 UTC, chrighter commented on tasks/11.html
> +                    border: 3px solid red;
![image](https://user-images.githubusercontent.com/22082557/47358760-29faf400-d6e4-11e8-8c5f-a3edcb197067.png)
Цвета не соответствуют макету

2018-10-23 12:28 UTC, chrighter commented on tasks/11.html
> +                input:hover
Цвет `#6698ff` должен быть при _фокусе_, а не при _наведении_

2018-10-23 12:28 UTC, chrighter commented on tasks/12.html
> +                div:nth-child(5)
Рабочее решение, но здесь предполагалось определять пустой элемент или нет

2018-10-23 12:28 UTC, chrighter commented on tasks/14.html
> +                    content: '+';
![image](https://user-images.githubusercontent.com/22082557/47358952-bc9b9300-d6e4-11e8-9288-a4ed5e3f7752.png)
Не соответствует макету

2018-10-23 12:28 UTC, chrighter commented on tasks/15.html
> +                [href='archive2.zip']:after
Рабочее решение, но давай решим задачку, не указывая явно `archive` и `archive2`

2018-10-23 12:28 UTC, chrighter commented on tasks/15.html
> +                    content: '↓';
Давай зададим стрелочку с помощью `utf8`-символа

2018-10-23 12:28 UTC, chrighter commented on tasks/15.html
> +                    content: '↓';
![image](https://user-images.githubusercontent.com/22082557/47359057-19974900-d6e5-11e8-90a4-146c47e32ae7.png)
Не соответствует макету

2018-10-23 12:28 UTC, chrighter commented on tasks/16.html
> +                    <div class="c7" style="background:#ffff66" ></div>
В условии задачи написано, что можно менять стили только внутри `<style>`

2018-10-23 12:28 UTC, chrighter commented on tasks/17.html
> +                input:checked ~ input:not(:checked)
🔥🔥

2018-10-23 12:28 UTC, chrighter commented on tasks/18.html
> +                }
![image](https://user-images.githubusercontent.com/22082557/47359218-91fe0a00-d6e5-11e8-848c-64f5509cb248.png)

Я навела на центральный кубик, в этот момент он должен стать ярче, чем дефолтный цвет (у тебя это реализовано), а остальные кубики должны стать бледнее, чем дефолтный цвет (у тебя этого не происходит)

Кажется, не хватает стилей

2018-10-23 12:28 UTC, chrighter commented on tasks/6.html
> +                    color: deeppink;
Цвет не соответствует тому, который используется в макете

2018-10-23 12:28 UTC, chrighter commented on tasks/8.html
> +                [href*='.com']
А если у тебя внезапно появится домены `.edu`, `.gov`, `.org` и тд, ты все их перечислять будешь?

Давай сделаем более универсальный отбор внешних относительно `my-site.ru` ресурсов

2018-10-23 12:28 UTC, chrighter commented on tasks/9.html
> +                    color: #ff6;
Цвет не соответствует тому, который используется в макете

2018-10-23 12:28 UTC, chrighter commented on tasks/9.html
> +                [href='https://ya.ru']:hover
При наведении на `pseudolink` ничего не происходит

2018-10-23 12:28 UTC, chrighter commented on tasks/9.html
> +                [href='https://ya.ru']:active
Повторное нажатие на посещенную ссылку не работает

2018-10-23 12:28 UTC, chrighter commented on tasks/5.html
> +                    color: white;
Давай везде цвета задавать в этой задаче в `hex` для единообразия, раз уж изначально они в условии были даны в `hex`

2018-10-23 12:28 UTC, chrighter commented on tasks/20.html
> +                div:nth-child(n+3) div:nth-child(n)
Давай попробуем не писать стили в теги, где это возможно, ведь теги даны, чтобы размечать структуру, а css классы как раз про отображение

2018-10-23 20:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 21:22 UTC, chrighter requested changes
🍅

2018-10-24 21:22 UTC, chrighter commented on tasks/15.html
> +                        <a href="archive.zip"  download target="_top">Ссылка 3</a>
Зачем пробел перед `download`?

2018-10-24 21:22 UTC, chrighter commented on tasks/9.html
> +                [href='https://ya.ru']:active
При нажатии на `pseudolink` она не становится чёрного цвета, как в макете

2018-10-24 21:22 UTC, chrighter commented on tasks/12.html
> +                div:empty
👍

2018-10-24 21:22 UTC, chrighter commented on tasks/15.html
> +                [href$='.zip']:after
👍

2018-10-24 21:22 UTC, chrighter commented on tasks/8.html
> +               a:not([href$='/info']):not([href*='my-site.ru'])
👍

2018-10-24 21:22 UTC, chrighter commented on tasks/9.html
> +                [href='https://ya.ru']:hover
При наведении на посещенную ссылку она тоже должна менять цвет на `#ff6698`

2018-10-24 21:22 UTC, chrighter commented on tasks/20.html
> +                .red-gt2:nth-child(n+3) div:nth-child(n)
👍 

Но можно было просто `> div` вместо div:nth-child(n) `div:nth-child(n)`

2018-10-24 21:22 UTC, chrighter commented on tasks/7.html
> +              div:not(:first-child):not(:last-child)
Давай посмотрим не на порядок элементов в `DOM`, а на `alt`

2018-10-24 21:37 UTC, chrighter requested changes

2018-10-24 21:37 UTC, chrighter commented on tasks/2.html
> +                    border: 2px solid #000;
Необязательно, ведь ты уже указал этот стиль -`border: 2px solid #000` - для `.c1`

2018-10-25 05:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 06:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-25 06:10 UTC, chrighter approved these changes
🍏

2018-10-25 06:10 UTC, closed without merging